### ISSUE TITLE
Feature/Handle Reserved Names

### ISSUE THREAD

**Issue by nalchevanidze** [morpheusgraphql/morpheus-graphql#207]
reserved name `type` is converted to `type'`. 

there are  `convertToJSONName` and `convertToHaskellName` [functions](https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Types/Internal/Value.hs#L20) responsible for it. 

TODO: 
- extend it to support all reserved Names: `data`, `default`, ....
- update API Documentation

**Comment by horus** [comment]
Hello @nalchevanidze,

Since a new issue has been opened, we move on here.

I had read the related parts, the purpose of those functions were unclear to me at that time, due to the lack of a big picture. All I knew was: it parses & converts. The lesson learned here is we might need more comments in the original source code, and mention one can use `'` to avoid conflicts in the corresponding document.

I've tested your suggestions, it worked except for the generated documents. The output left the prime symbol just there.

An example:

```graphql
# toGraphQLDocument rootResolver
input TestArgs {
  type': String!
}
```

...I am afraid this isn't the intended behavior. The latest GraphQL spec:

```
InputFieldsDefinition
    { InputValueDefinitionlist }
InputValueDefinition
    Description Name : Type DefaultValue Directives
Name ::
    /[_A-Za-z][_0-9A-Za-z]*/
```
... which allows the use of "type" as field name, so we might want get that fixed, too:

```graphql
# fixed
input TestArgs {
  type: String!
}
```

I don't know whether you're already working on the solution, but if you're busy, I'm willing to extend the `convertTo*` functions first, then try to get rid of the prime symbol in the output document.

**Comment by nalchevanidze** [comment]
my intention is that Haskell `type'` will be alias for `type`, but GraphQL schema will it read it just as `type`. 

i will be glad if you extend the `convertTo*` 

 thank you :)

**Comment by nalchevanidze** [comment]
done, thanks @horus
